pre_execute:
  cs_ratio:
    - "70%"
    - "50%"
    - "30%"

  task:
    - sentiment
    - ner
    - topic

  shared:
    topic:
      - tech
      - finance
      - shopping

    style:
      - casual

    tense:
      - Present

    perspective:
      - First Person

    cs_function:
      - Expressive

    cs_type:
      - Intrasentential

    conversation_type:
      - single_turn

    character_setting:
      nationality:
        first_language: Arabic
        second_language: English
      age:
        - "18-25"
      gender:
        - Male
      education_level:
        - College

    output_format: json
    use_tools: false

  sentiment:
    labels:
      - positive
      - negative
      - neutral
    intensity:
      - low
      - medium
    ambiguity:
      - low

  ner:
    entity_types:
      - PER
      - ORG
      - LOC
    min_entities:
      - 2
    max_entities:
      - 3
    must_include_types:
      - PER
      - ORG
    allow_code_switched_entities:
      - true

  topic:
    topics:
      - business
      - education
      - health
      - shopping
      - medical
      - sports
      - tech
      - finance
      - social

on_execute:
  round: 1
  verbose: true
