#!/usr/bin/env bash
# Compute control BEFORE any Topic-1080 generation: does the EXISTING fixed Topic-540
# corpus keep improving with more training, at 8 epochs = 272 optimizer steps?
#
# 540 rows / batch 16 = 34 steps per epoch; 34 x 8 = 272. --max_steps 272 is passed
# explicitly (mirroring the 136-step runs, which passed --max_steps 136) so the budget
# is exact rather than inferred from epoch rounding.
#
# Paired against experiment_topic_matched_compute/mc540_seed{42,43,44} (136 steps).
# TRAINING DURATION IS THE ONLY DIFFERENCE. Everything else is byte-identical:
# xlm-roberta-base, batch 16, grad_accum 1, lr 2e-5, max_length 256, fp16,
# gradient_checkpointing OFF, optim adamw_torch, 9 labels in the frozen order,
# NO dev set, load_best OFF (final-step model).
#
# CHECKPOINT SELECTION NOTE: the request asked for dev-based selection, but the only
# topic dev set in the repo is ArEnTC, which this study line explicitly excludes
# (run_topic_learning_curve.sh:11-15), and adding selection would confound duration
# with selection in the paired difference. Kept load_best OFF; flagged in the report.
#
# Silver-1163 is FINAL EVALUATION ONLY. No data is generated by this script.
set -u
cd "$(dirname "$0")/.."
PY=python
export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 PYTHONUNBUFFERED=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:128

SILVER=experiments/outputs/multi_agent_bert/experiment_silver_topic540/silver_full1163_ordered.jsonl
FULL540=data/Topic/generated/merged/switchlingua_topic_train_540_60perlabel.jsonl
OUTR=experiments/outputs/multi_agent_bert/experiment_topic540_272steps
CK=experiments/checkpoints/_272_tmp
STEPS=272
mkdir -p "$OUTR"

for SEED in 42 43 44; do
  TAG="mc540x2_seed${SEED}"
  OUT="$OUTR/$TAG"; mkdir -p "$OUT"; rm -rf "$CK"

  echo "===== START $TAG  train=$(basename "$FULL540")  steps=$STEPS  $(date +%H:%M:%S) ====="
  "$PY" scripts/finetune_transformer_classifier.py \
    --train "$FULL540" \
    --labels business education health shopping medical sports tech finance social \
    --base_checkpoint xlm-roberta-base --output_dir "$CK" \
    --max_steps "$STEPS" --batch_size 16 --grad_accum 1 --lr 2e-5 --max_length 256 \
    --seed "$SEED" --fp16 \
    > "$OUT/finetune.log" 2>&1
  echo "  finetune exit=$? $(date +%H:%M:%S)"

  "$PY" evaluate_pipeline.py \
    --dataset "$SILVER" --config src/config/default.yaml --active_task topic_classification \
    --pipeline_mode primary_only --mode full_pipeline \
    --primary_model transformer --transformer_checkpoint "$CK" \
    --transformer_device cuda --output_dir "$OUT" --run_id "$TAG" \
    > "$OUT/eval.log" 2>&1
  echo "  eval exit=$? $(date +%H:%M:%S)"

  rm -rf "$CK"
  echo "  checkpoint removed; free: $(df -h /c | tail -1 | awk '{print $4}')"
done
echo "===== 272-STEP CONTROL DONE $(date +%H:%M:%S) ====="
